// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildApp(arg1) {
  return window['go']['main']['App']['BuildApp'](arg1);
}

export function GetDistInfo(arg1) {
  return window['go']['main']['App']['GetDistInfo'](arg1);
}

export function OpenDistFolder() {
  return window['go']['main']['App']['OpenDistFolder']();
}

export function OpenIconFile() {
  return window['go']['main']['App']['OpenIconFile']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function OpenTempFolder() {
  return window['go']['main']['App']['OpenTempFolder']();
}

export function UploadDistZip(arg1) {
  return window['go']['main']['App']['UploadDistZip'](arg1);
}

export function ValidateIcon(arg1) {
  return window['go']['main']['App']['ValidateIcon'](arg1);
}
