// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildApp(arg1:main.BuildConfig):Promise<void>;

export function GetDistInfo(arg1:string):Promise<main.DistInfo>;

export function OpenDistFolder():Promise<string>;

export function OpenIconFile():Promise<string>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function OpenTempFolder():Promise<string>;

export function SanitizeName(arg1:string):Promise<string>;

export function UploadDistZip(arg1:string):Promise<string>;

export function ValidateIcon(arg1:string):Promise<string>;
